### ISSUE TITLE
Ensure tests coverage

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch-v4#77]
- [x] Configuration validation
- [x] Configuration utilities
- [x] Content types service
- [ ] Meilisearch service. Missing:
  - [ ] getCollectionsReport
  - [ ] addOneEntryInMeiliSearch
  - [ ] addCollectionInMeiliSearch
  - [ ] getCollectionsWithSameIndex
  - [ ] emptyOrDeleteIndex
  - [ ] updateCollectionInMeiliSearch
  - [ ] removeCollectionFromMeiliSearch
  - [ ] getCollectionsIndexedInMeiliSearch
- [x]  Store service. Missing: all.

**Comment by curquiza** [comment]
Checked with @bidoubiwa, implemented in the official strapi plugin. Closing this then
